# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimage', '0002_auto_20180930_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
    ]
